---
title: "R Notebook"
output: html_notebook
---

## Creation of vectors
the c() function use to create 'em
```{r}
x<-c(0.5,0.6) ## numeric  
y<-c(TRUE,FALSE) ##logical  or T F
z<-c("a","b","c") ## character 
i<-9:29 ##integer
c<-c(1+0i,2+4i) ## complex

```
Using vector(type,...) function
```{r}
x<-vector("numeric",length = 10)
```

### Mixing Objects  
what about this ??
```{r}
y<-c(1.7,"a") ## convert all to character
y<-c(T,2)
y<-c("a",T)
```

### Explicit Coercion  
use as.type(var) to convert var
```{r}
x<-0:6;
class(x)
as.numeric(x)
as.logical(x)
as.character(x)
```
sametime doesn't work
```{r}
x<-c("a","b","c");
as.numeric(x)
```
## Lists
```{r}
l<-list(1,"a",TRUE,1+4i)
l
```
## Matrices 
vector with dimesions 
```{r}
m<-matrix(nrow = 2,ncol = 3); 

m
dim(m) ## return rows,cols

attributes(m)

```
Matrice r considered as column wise
```{r}
m<-matrix(1:6,nrow=2,ncol = 3)
print(m)
```
Matrices can be created direclty from a vector
```{r}
#initialize matrix
m<-1:10 #assign to it numbers from1 to 10
m
#setup the numbers of rows and cols
dim(m)<-c(2,5) ## 2 row 5
m
```
Create matric by binding colow and rowns (cbind and rbing)
```{r}
x<-1:3
y<-10:12
z<-9:11
cbind(x,y)
rbind(x,y,z)
```

